### PR TITLE
Update playbooks and travis so that it passes.

### PR DESCRIPTION
**Pull request by brucellino**
This fixes  the ansible roles and playbooks that were causing travis to report broken builds. Several updates have been made, so several roles - mostly refactoring of tasks according to a similar style. 

I have run the syntax check on all of the tested playbooks, and there are at least on syntax errors. some of the roles are still not fully implemented though.

### CODE REVIEW

**Comment by brucellino** [comment]
@bazinski All tests have passed. A cursory glance is necessary from you :smile:

**Comment by bazinski** [comment]
why the sudo for xrootd ? and then changing it to become?

**Comment by brucellino** [comment]
I stand to be corrected on the xrootd deployment. That's  what I had in the original role from a while back, but as far as I know this role has never been applied anywhere on our infrastructure... Can you give me a link to the xrootd deploy guide  where it says how to deploy ?

**Comment by bazinski** [comment]
When I used to do it manually before eos it was always as xrootd user.
Looking at my eos config for the FSTs they run as daemon which is probably similarl to what you are doing.

**Comment by brucellino** [comment]
Ok - we'll have to remember this for later. for now the pull is merged. thanks for the review  :+1:

**Comment by bazinski** [comment]
It actually brings us back to a discourse thing i wrote a while back about testing full installs, but we can discuss at foundry thing.

**Pull request merged**
